name: Sylvia Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cd-sylvia:
    name: "Continuous Deployment - Sylvia"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify OKD to Build and Deploy
        run: |
          curl -X POST ${{ secrets.CD_BUILD_WEBHOOK_SYLVIA }}
